### ISSUE TITLE
Reflections

### ISSUE THREAD

**Issue by shelterx** [onnoj/DeusExEchelonRenderer#13]
Not sure if this is a bug, you decide.
But some surfaces are reflective/shiny with OpenGL/D3D, like some floors, for example like the one in the first room in the training level.
I'm not sure if there should be similar "effects" when using EchelonRenderer?

**Comment by onnoj** [comment]
So, sadly this is where the scope of the renderer ends, and where hopefully future mods will pick up.
In a raytracing renderer, reflections would need to be set on the material itself. This is where you'd need a proper RTX Remix mod that introduces new texturemaps to the scene.

So for a scene such as this one:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/b6a27c42-925c-42d4-b6d2-b07cc52b2ebf)
the default material (which is just an albedo texture) won't reflect.

But, if the floor were to be replaced with a proper material (albedo + normal map + roughness map + metallic map), you'd get reflections:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/99ea82e4-d7ab-4a94-838a-facb5a2a910c)
This is still the albedo texture, but with a manual tweak to it to have 0.01 roughness (ie almost a mirror) and slightly less metallic (not sure how to describe that, it's effectively organic versus shiny). With actual full PBR maps, you'd get a much more realistic look.

**Comment by onnoj** [comment]
I am however thinking about a way to at least some specific mirrors to work. There are some cases in the game (like the Hong Kong underground disco, and most bathroom mirrors) where mirrors are done by flagging a surface as 'PF_MIRROR' and not having a texture assigned. I think the renderer might be able to detect that and swap in a special 'mirror' texture.

**Comment by shelterx** [comment]
Ok, thanks for the response. However, I'm curious how the OpenGL renderer know that the floor is reflective? Hardcoded?

**Comment by onnoj** [comment]
Basically, in Deus Ex/UE, the renderer _doesn't_ know anything about reflections. From its perspective, the reflection is just another room.

What happens in the game engine, is that when it's doing the occlusion pass (ie, it's figuring out which triangles are visible and which ones aren't), the algorithm the games used in the day made it very easy to have mirrors (and portals!). Normally, when traversing the BSP tree, if it'd hit a solid surface the engine just rasterizes it and sends it to the renderer as a bunch of triangles. 
But if that surface is marked a mirror, it basically travels back up the tree in reverse order with the Z-Axis flipped, sending a bunch more triangles to the renderer that make up the reflected space. ie, think of it as the game constructing an identical looking room behind the mirror surface, _before_ sending it to the renderer.

In modern games, this trick doesn't work (which is why mirrors effectively disappeared from games until raytracing become more commonplace) because different algorithms are used; it just became much more efficient to sort your geometry front-to-back and let the gpu hardware figure it all out.

That same trick also doesn't work with raytracing anymore; for your GPU to be able to reliably shoot rays, the geometry has to be stable and sensible. Ie, with the same trick, the mirrored geometry would be sticking through actual geometry behind the mirror.

But, there are two things that we can do:
A) For actual mirrors (which in Deus Ex tend to have a black or no texture and have their surface marked as 'mirror'), the Echelon renderer can try and intercept that, and then perform a texture replacement with a very reflective texture.
B) For reflective surface textures, it's largely the same trick the engine does, but I'd have to look how Deus Ex/UE actually blends the texture with the reflection. This is probably where I can't do a texture swap, and where the original texture would have to be authored to be reflective.

**Comment by shelterx** [comment]
Thanks again, very nice explanation! So techically it's more difficult to do with RTX even if we know that a specific texture (or room) in a level should be slightly reflective.

**Comment by onnoj** [comment]
Yes, correct, something needs to tell the raytracer which parts of the texture is reflective. Right now, the raytracer only receives the albedo texture (ie, just contains the color).

And this is effectively what the RTX Toolkit is for, it allows you to replace an original texture with new ones that do contain that information: 
https://www.a23d.co/blog/different-maps-in-pbr-textures

ie, this (original albedo texture):
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/b2eb4f37-614b-4686-bb5d-23c6b65c0572)

would need to be turned into this:
(upscaled albedo)
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/38b118df-e001-460c-b03f-22d938906e38)
+
(normal map)
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/a5a399dd-22b2-469a-bddd-e065e6f82489)
+
(roughness)
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/e1f54b76-0d71-4ff3-afdf-73b1d2a7ca38)

As an example, those three were converted and upscaled by a neural network, and are not quite right. But, the real thing would look something like this:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/f3ec66c3-7a5a-4a03-9b87-7199766d44e6)
https://www.cgbookcase.com/textures/marble-08/

**Comment by shelterx** [comment]
Ok, that makes even more sense, You're not going to retexture the game, you provide the renderer which is more than enough. :)

**Comment by MamiyaOtaru** [comment]
roughness 0, flat normal map: 
![reflections](https://github.com/onnoj/DeusExEchelonRenderer/assets/2042826/ca584d05-f38c-4067-8f59-dd3d44e42d2f)
