### ISSUE TITLE
Game hangs with Echelon Renderer

### ISSUE THREAD

**Issue by shelterx** [onnoj/DeusExEchelonRenderer#3]
I tried this mod and it just hangs Deus Ex when starting it.
I tried both in Windows and Linux (proton), no difference.
Game works fine with all other renderers.

Nvidia RTX 4070
Latest drivers
Higher res textues installed for DeusEx.

**Comment by onnoj** [comment]
Hi, can you include the version numbers, including of RTX remix? Can you also try on a clean install of Deus Ex?

**Comment by shelterx** [comment]
Deus Ex GOTY
remix-0.4.1-release
DeusExEchelonRenderer-v0.1.13
DeusExe-v5.3

I will try a reinstall of the game, Windows is freshly installed.

**Comment by shelterx** [comment]
Tried a reinstall, didn't work. With the original exe I get sound but it still hangs.

**Comment by onnoj** [comment]
Can you provide a memory dump by going into the windows task manager, right click the DeusEx.exe process, and clicking "Create Memory Dump File". If the file is too big to be attached here (you may need to 7z it), you could also try sending it to me over Discord (user: echelon4) or via 📧: stuff at onnoj dot net

**Comment by shelterx** [comment]
You can download it here:
https://drive.google.com/file/d/1e62fs7n1I7vlcpLUT2Rm6Nz3kT8-V_9k/view?usp=drive_link

**Comment by onnoj** [comment]
So, I had a look at the memory dump, and it looks like the remix wrapper gets stuck while we're enumerating the different display modes. Do you happen to have a lot of (virtual) displays connected? Maybe remix choked on those.

I've cleaned up the code a bit (previously it was trying to dump all modes from ALL adapters), now it just works on the primary display adapter.

Can you give the latest version a go? Currently that's https://github.com/onnoj/DeusExEchelonRenderer/releases/tag/v0.1.15
If you still have the issue, can you then try the following?
A) Grab the debugoptimized version of RTX Remix: https://github.com/NVIDIAGameWorks/rtx-remix/releases
B) Run the game in _windowed_ mode
C) Grab another memory dump while it hangs.
E) Can you attach various log files? There should be a d3d9.log and DeusEx_d3d9.log in the DeusEx system folder  file. There should also be a deusex.log file in either the DeusEx\System folder, or if you're using Kentie's Deus Exe, it should be in the DeusEx folder in the My Documents folder.

**Comment by shelterx** [comment]
No go :(
I do have secondary monitor and a Windows secondary virtual desktop. I also have a secondary virtual desktop when I run Linux.
[deusex-logs-hang.zip](https://github.com/onnoj/DeusExEchelonRenderer/files/14931737/deusex-logs-hang.zip)
The deusex.log files were both empty so i didn't include those.
New memdump:
https://drive.google.com/file/d/19aDObu1DY_EiQBRVYbhqiJ3q2H23GfH2/view?usp=sharing

Update:
Disabling the virtual desktop in windows did not help.

**Comment by onnoj** [comment]
Hi, there was no DeusEx.log in your documents Deus Ex folder?
detected.log only shows the old renderer being used: 
> Log: Detecting D3DDrv.D3DRenderDevice
> Log: Bound to D3DDrv.dll

Out of curiosity, in the dump I see that detoured.dll is loaded, from the system folder. Do you know where that came from? It doesn't ship with Deus Ex or RTX Remix by default.

**Comment by shelterx** [comment]
I'm so confused now... 
The detoured.dll was from an older deusex.exe version, so I went and checked and found a newer version than I had. Which's weird because I downloaded it from the same page.

I tried starting the game again, it hanged.
Then I deleted the log files so I was sure every log was fresh, then I started the game and it worked fine (???) however the training mission was very dark at the begining?
So I thought, let's try fullscreen instead of Window mode, the game hang again so I went and deleted the logs to give you fresh ones, then I started the game again in Fullscreen... and... it worked????
And now it works every time I start it but it's very dark, not sure if it's supposed to be that. Toggling the lamp in the training mission didn't do much either.

**Comment by onnoj** [comment]
Glad you got it (mostly) to work! It was probably a weird/old config file somewhere.

And yeah, by default, the game is actually pretty dark. You can increase the brightness in the options, it'll increase the actual brightness of the lights (rather than any gamma curves), I think 0.75 is a comfy setting, but, what works best depends on your monitor.

That being said, the training area is weirdly dark, for some reason. It might be a bug, it's on my TODO list to investigate. This renderer uses the original source data of the light position and intensity, and maybe that data is incorrect for the training area.

As for the lamp toggle (F12), it doesn't work very well with the current official version of RTX Remix (which is more than 2 months old now!), but you can try the latest cutting edge from their development branch. To do so:

1. Go to the bridge-remix artifacts: https://github.com/NVIDIAGameWorks/bridge-remix/actions/workflows/build.yml
2. click the latest green build
3. scroll down, there should be three files, download the 'release' artifact. Extract theses files to your Deus Ex system folder, overwriting the existing files.
4. Now go to the dxvk-remix artifacts: https://github.com/NVIDIAGameWorks/dxvk-remix/actions/workflows/build.yml
5. click the latest green build
6. Once more, scroll down, download the 'release' artifact. Extract these files to the .trex folder in your Deus Ex system folder, overwriting the existing files. Be sure to put them in the .trex folder!!

**Comment by shelterx** [comment]
Just a quick note, I updated the runtimes like you said, the game hang the first launch, the second launch it worked. Might still be a bug hiding somewhere.

**Comment by onnoj** [comment]
Well, there is always a very brief hang after installing a new driver or
rtx remix version, I think rtx remix is compiling shaders, maybe it's that.
Maybe for some reason it takes a lot longer for you or gets stuck. Might be
interesting to just let it run for 10 minutes or so
