### ISSUE TITLE
Gmdx support 💡[FEATURE] ...

### ISSUE THREAD

**Issue by Assurokilwr** [onnoj/DeusExEchelonRenderer#8]
https://www.moddb.com/mods/gmdx

**Comment by Assurokilwr** [comment]
Or https://www.moddb.com/mods/deus-ex-revision

**Comment by onnoj** [comment]
Hi,

This is beyond the feature scope of the renderer. 
Technically, it should already work, if it's not the case it's likely due to modifications these mods made to the game engine.

You may want to contact the modding teams and ask if they can look into it.

If there is a bug with the renderer that prevents it from working with these mods, I will happily accept a detailed bug report, or a merge request from their teams.
